openapi: 3.0.0
info:
  title: Product Service API
  description: API for managing products
  version: 1.0.0
servers:
  - url: https://{apiId}.execute-api.{region}.amazonaws.com/{stage}
    variables:
      apiId:
        default: zzdhws7qx3
        description: API Gateway ID
      region:
        default: eu-north-1
        description: AWS Region
      stage:
        default: prod
        description: API Stage
paths:
  /products:
    get:
      summary: Get all products
      description: Returns a list of all products
      operationId: getProductsList
      tags:
        - products
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Internal Server Error
  /products/{productId}:
    get:
      summary: Get product by ID
      description: Returns a single product by its ID
      operationId: getProductById
      tags:
        - products
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '500':
          description: Internal Server Error
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: number
      required:
        - id
        - title
        - price
        - count
